name: app_lints
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none
resolution: workspace

environment:
  sdk: ^3.10.3

dependencies:
  lints: ^6.0.0
  flutter_lints: ^6.0.0

topics:
  - lints